version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/scripts"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels: ["dependencies", "automation"]
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels: ["dependencies", "ci", "automation"]
    commit-message:
      prefix: "chore(ci)"
